// Aviation and avionics — the ICAO/US-1976 standard atmosphere, the airspeed
// chain, the drag polar and turn/glide performance.
//
// THE ATMOSPHERE IS A LAYERED DEFINITION, NOT A FORMULA. It is seven layers to
// 84.852 km geopotential, each with its own lapse rate, and the barometric
// relation CHANGES FORM at every isothermal layer (a power law where the lapse
// rate is non-zero, an exponential where it is zero). Applying one layer's
// formula across a boundary gives a plausible wrong number and no error, which
// is why the layer table is walked rather than approximated.
//
// The base TEMPERATURES and lapse rates below are the published definition. The
// base PRESSURES are deliberately NOT typed in: they are generated by walking the
// recurrence from sea level, so the profile is continuous by construction and a
// mistyped digit cannot put a step in it.
//
// THE AIRSPEED CHAIN is the other trap, and it is the same shape as the clock
// skew in chips.ts: each correction has a direction, and applying one backwards
// leaves a plausible number. TAS -> EAS divides by sqrt(sigma) the right way only
// once; CAS is not EAS with a density correction but is defined through the
// IMPACT PRESSURE, so the compressibility term does not cancel.
//
// IAS is NOT computed. The step from CAS to IAS is instrument and position error
// — a property of a particular airframe and installation, published as a
// correction card — and inventing it would be exactly the failure this project
// avoids elsewhere.

/** Standard gravity, m/s^2 (exact by definition). */
export const G0 = 9.80665;
/** Specific gas constant for dry air, J/(kg·K) — R-star divided by M0 in the 1976 model. */
export const R_AIR = 8314.32 / 28.9644;
/** Ratio of specific heats for air. */
export const GAMMA = 1.4;
/** Sea-level standard pressure, Pa. */
export const P0 = 101325;
/** Sea-level standard temperature, K. */
export const T0 = 288.15;
/** Effective Earth radius for the geopotential conversion, m. */
export const R_EARTH = 6356766;

/** g0*M0/R* , K/m — the exponent constant of the barometric formula. */
const GMR = (G0 * 28.9644) / 8314.32;

interface Layer {
  /** Base geopotential altitude, m. */
  h: number;
  /** Lapse rate dT/dh, K/m. Zero marks an isothermal layer. */
  lapse: number;
  /** Base temperature, K. */
  t: number;
  /** Base pressure, Pa — COMPUTED below, never typed. */
  p: number;
}

/**
 * The seven layers of the 1976 standard atmosphere, to 84.852 km geopotential.
 * Base pressures are filled by walking the recurrence so the profile cannot have
 * a discontinuity in it.
 */
export const LAYERS: Layer[] = (() => {
  const spec: Array<[number, number, number]> = [
    [0, -0.0065, 288.15],
    [11000, 0.0, 216.65],
    [20000, 0.001, 216.65],
    [32000, 0.0028, 228.65],
    [47000, 0.0, 270.65],
    [51000, -0.0028, 270.65],
    [71000, -0.002, 214.65],
    [84852, 0.0, 186.946],
  ];
  const out: Layer[] = [];
  let p = P0;
  for (let i = 0; i < spec.length; i++) {
    const [h, lapse, t] = spec[i];
    out.push({ h, lapse, t, p });
    if (i + 1 < spec.length) {
      const dh = spec[i + 1][0] - h;
      p = lapse === 0 ? p * Math.exp((-GMR * dh) / t) : p * Math.pow(t / (t + lapse * dh), GMR / lapse);
    }
  }
  return out;
})();

export interface AtmosphereResult {
  /** Geopotential altitude actually used, m. */
  geopotentialM: number;
  temperatureK: number;
  pressurePa: number;
  densityKgM3: number;
  /** Speed of sound, m/s. */
  soundSpeedMs: number;
  /** Density ratio to sea level, used for EAS. */
  sigma: number;
  /** Pressure altitude for a non-standard sea-level setting, m. */
  layerIndex: number;
  notes: string[];
}

/**
 * The standard atmosphere at a GEOMETRIC altitude (what an altimeter measures as
 * height), converted internally to the geopotential altitude the model is
 * defined in.
 *
 * `deltaTempK` offsets the temperature from standard (ISA+10 and so on). It
 * changes temperature and density but NOT pressure: pressure at a given
 * geopotential height is fixed by the model, and a warm day makes the air thinner
 * at the same pressure rather than raising the pressure.
 */
export function atmosphere(geometricM: number, deltaTempK = 0): AtmosphereResult | null {
  if (!Number.isFinite(geometricM) || !Number.isFinite(deltaTempK)) return null;
  // Geopotential from geometric: H = r*z/(r+z).
  const h = (R_EARTH * geometricM) / (R_EARTH + geometricM);
  const top = LAYERS[LAYERS.length - 1].h;
  if (h < -5000 || h > top) return null;

  const notes: string[] = [];
  let i = 0;
  for (let k = 0; k < LAYERS.length; k++) if (h >= LAYERS[k].h) i = k;
  const L = LAYERS[i];

  const dh = h - L.h;
  const tStd = L.t + L.lapse * dh;
  const pressurePa = L.lapse === 0 ? L.p * Math.exp((-GMR * dh) / L.t) : L.p * Math.pow(L.t / tStd, GMR / L.lapse);

  const temperatureK = tStd + deltaTempK;
  if (temperatureK <= 0) return null;
  const densityKgM3 = pressurePa / (R_AIR * temperatureK);
  const rho0 = P0 / (R_AIR * T0);

  if (Math.abs(geometricM - h) > 1) {
    notes.push(
      `Geometric ${geometricM.toFixed(0)} m is ${h.toFixed(0)} m GEOPOTENTIAL, which is what the ` +
        "model is defined in. The two differ because gravity weakens with height, and ignoring " +
        "it costs about 0.5% of the altitude at 30 km.",
    );
  }
  if (deltaTempK !== 0) {
    notes.push(
      `ISA${deltaTempK > 0 ? "+" : ""}${deltaTempK} K: temperature and DENSITY move, pressure does ` +
        "not. Pressure at a geopotential height is fixed by the model — a warm day thins the air " +
        "at the same pressure rather than raising it, which is why hot-and-high hurts performance.",
    );
  }
  notes.push(
    `Layer ${i} (base ${L.h} m, lapse ${(L.lapse * 1000).toFixed(1)} K/km). The barometric ` +
      "relation is a power law in the sloped layers and an exponential in the isothermal ones; " +
      "using one across a boundary is a silent error, so the table is walked layer by layer.",
  );

  return {
    geopotentialM: h,
    temperatureK,
    pressurePa,
    densityKgM3,
    soundSpeedMs: Math.sqrt(GAMMA * R_AIR * temperatureK),
    sigma: densityKgM3 / rho0,
    layerIndex: i,
    notes,
  };
}

/** Pressure altitude for a given station pressure, m geopotential. */
export function pressureAltitude(pressurePa: number): number | null {
  if (!Number.isFinite(pressurePa) || pressurePa <= 0) return null;
  if (pressurePa > LAYERS[0].p) {
    // Below sea level in the standard model — still well defined in layer 0.
    const L = LAYERS[0];
    return (L.t / L.lapse) * (Math.pow(L.p / pressurePa, L.lapse / GMR) - 1);
  }
  // ABOVE THE MODEL, REFUSE — do not extrapolate the top isothermal layer upward.
  // atmosphere() refuses above 84.852 km and this must agree with it: without the
  // guard a pressure of 0.0037 Pa returned 110 km, an altitude the 1976 standard
  // does not describe with these equations at all.
  const top = LAYERS[LAYERS.length - 1];
  if (pressurePa < top.p) return null;

  let i = 0;
  for (let k = 0; k < LAYERS.length; k++) if (pressurePa <= LAYERS[k].p) i = k;
  const L = LAYERS[i];
  if (L.lapse === 0) return L.h + (-L.t / GMR) * Math.log(pressurePa / L.p);
  return L.h + (L.t / L.lapse) * (Math.pow(L.p / pressurePa, (L.lapse / GMR)) - 1);
}

export interface AirspeedResult {
  tasMs: number;
  easMs: number;
  casMs: number;
  mach: number;
  /** Impact (dynamic-plus-compressibility) pressure, Pa. */
  impactPa: number;
  /** Incompressible dynamic pressure 1/2 rho V^2, Pa. */
  dynamicPa: number;
  notes: string[];
}

/**
 * The airspeed chain from TAS at a given density and pressure.
 *
 *   EAS = TAS * sqrt(rho/rho0)                     — a density correction only
 *   qc  = p * [(1 + 0.2 M^2)^3.5 - 1]              — impact pressure, subsonic
 *   CAS = a0 * sqrt(5 * [(qc/p0 + 1)^(2/7) - 1])   — the same qc read at sea level
 *
 * CAS IS NOT EAS WITH A DENSITY FIX. Both come from the same impact pressure, but
 * CAS is what a sea-level-calibrated instrument reads from that pressure, so the
 * compressibility term does not cancel. At low speed and low altitude the three
 * converge, which is exactly why an error here hides in the cases people check.
 */
export function airspeeds(tasMs: number, densityKgM3: number, pressurePa: number): AirspeedResult | null {
  if (![tasMs, densityKgM3, pressurePa].every(Number.isFinite)) return null;
  if (tasMs < 0 || densityKgM3 <= 0 || pressurePa <= 0) return null;

  const rho0 = P0 / (R_AIR * T0);
  const a0 = Math.sqrt(GAMMA * R_AIR * T0);
  const a = Math.sqrt((GAMMA * pressurePa) / densityKgM3);
  const mach = tasMs / a;

  const easMs = tasMs * Math.sqrt(densityKgM3 / rho0);
  const impactPa = pressurePa * (Math.pow(1 + 0.2 * mach * mach, 3.5) - 1);
  const casMs = a0 * Math.sqrt(5 * (Math.pow(impactPa / P0 + 1, 2 / 7) - 1));

  const notes: string[] = [
    "CAS is derived through the IMPACT PRESSURE, not from EAS by a density correction: both " +
      "follow from the same qc, but CAS is what a sea-level-calibrated instrument reads from it, " +
      "so the compressibility term does not cancel.",
    "IAS is NOT computed. CAS to IAS is instrument and position error, a property of the " +
      "particular airframe and installation published on a correction card — it cannot be " +
      "derived from these numbers.",
  ];
  if (mach > 1) {
    notes.push(
      `Mach ${mach.toFixed(3)} is SUPERSONIC. The subsonic impact-pressure relation used here is ` +
        "not valid through a shock: above Mach 1 the Rayleigh pitot formula applies instead, so " +
        "the CAS shown is out of its range.",
    );
  } else if (mach > 0.3) {
    notes.push(
      `Mach ${mach.toFixed(3)}: compressibility matters above about 0.3, which is why EAS and CAS ` +
        "have separated here.",
    );
  }

  return {
    tasMs,
    easMs,
    casMs,
    mach,
    impactPa,
    dynamicPa: 0.5 * densityKgM3 * tasMs * tasMs,
    notes,
  };
}

export interface PolarResult {
  cl: number;
  cd: number;
  liftToDrag: number;
  dragN: number;
  /** Induced-drag factor k = 1/(pi*AR*e). */
  k: number;
  /** Best lift-to-drag ratio available from this polar. */
  bestLd: number;
  /** CL at which that occurs. */
  clAtBestLd: number;
  /** Speed at which that occurs at this density, m/s. */
  speedAtBestLdMs: number;
  /** Stall speed at this density and CLmax, m/s. */
  stallSpeedMs: number | null;
  notes: string[];
}

/**
 * Level-flight lift, the parabolic drag polar and the best-L/D point.
 *
 * CD = CD0 + k*CL^2 with k = 1/(pi*AR*e). Best L/D occurs where induced drag
 * equals parasite drag, at CL = sqrt(CD0/k), giving (L/D)max = 1/(2*sqrt(CD0*k)).
 * Those two are DERIVED here rather than searched, so they cannot disagree with
 * the polar they came from.
 */
export function dragPolar(
  weightN: number,
  speedMs: number,
  wingAreaM2: number,
  densityKgM3: number,
  cd0: number,
  aspectRatio: number,
  oswald = 0.8,
  clMax?: number,
): PolarResult | null {
  const vals = [weightN, speedMs, wingAreaM2, densityKgM3, cd0, aspectRatio, oswald];
  if (!vals.every(Number.isFinite)) return null;
  if (weightN <= 0 || speedMs <= 0 || wingAreaM2 <= 0 || densityKgM3 <= 0) return null;
  if (cd0 <= 0 || aspectRatio <= 0 || oswald <= 0 || oswald > 1) return null;

  const q = 0.5 * densityKgM3 * speedMs * speedMs;
  const cl = weightN / (q * wingAreaM2);
  const k = 1 / (Math.PI * aspectRatio * oswald);
  const cd = cd0 + k * cl * cl;
  const dragN = q * wingAreaM2 * cd;

  const clAtBestLd = Math.sqrt(cd0 / k);
  const bestLd = 1 / (2 * Math.sqrt(cd0 * k));
  const speedAtBestLdMs = Math.sqrt((2 * weightN) / (densityKgM3 * wingAreaM2 * clAtBestLd));

  const notes: string[] = [
    "Best L/D is where induced drag EQUALS parasite drag, at CL = sqrt(CD0/k). Both it and the " +
      "speed it occurs at are derived from this polar rather than searched, so they cannot " +
      "disagree with it.",
  ];
  let stallSpeedMs: number | null = null;
  if (clMax !== undefined) {
    if (!Number.isFinite(clMax) || clMax <= 0) return null;
    stallSpeedMs = Math.sqrt((2 * weightN) / (densityKgM3 * wingAreaM2 * clMax));
    if (cl > clMax) {
      notes.push(
        `CL = ${cl.toFixed(3)} EXCEEDS the stated CLmax of ${clMax}: the wing is stalled at this ` +
          "speed and weight, so the drag figure above is not meaningful — the polar is a " +
          "pre-stall model.",
      );
    }
  }
  notes.push(
    "A parabolic polar with a constant Oswald factor is a cruise approximation: it does not " +
      "model compressibility rise, and it is not valid beyond CLmax.",
  );

  return { cl, cd, liftToDrag: cl / cd, dragN, k, bestLd, clAtBestLd, speedAtBestLdMs, stallSpeedMs, notes };
}

export interface TurnResult {
  loadFactor: number;
  radiusM: number;
  rateRadS: number;
  /** Time for a full 360, seconds. */
  periodS: number;
  /** Stall speed multiplied by sqrt(n). */
  stallInTurnMs: number | null;
  notes: string[];
}

/**
 * Level co-ordinated turn at a given bank angle.
 *
 *   n = 1/cos(phi),  R = V^2/(g*tan phi),  omega = g*tan(phi)/V
 *
 * STALL SPEED RISES WITH sqrt(n), not with n. At 60 degrees of bank the load
 * factor is 2 and the stall speed is up 41%, not 100% — a distinction that
 * decides whether a turn is flyable.
 */
export function levelTurn(bankDeg: number, speedMs: number, stallSpeedMs?: number): TurnResult | null {
  if (![bankDeg, speedMs].every(Number.isFinite)) return null;
  if (speedMs <= 0) return null;
  // 90 degrees of bank cannot be sustained in level flight: the lift vector is
  // horizontal and nothing carries the weight. Refused rather than returned as a
  // division by zero.
  if (Math.abs(bankDeg) >= 90 || bankDeg < 0) return null;

  const phi = (bankDeg * Math.PI) / 180;
  const loadFactor = 1 / Math.cos(phi);
  const tan = Math.tan(phi);
  const radiusM = tan === 0 ? Infinity : (speedMs * speedMs) / (G0 * tan);
  const rateRadS = (G0 * tan) / speedMs;

  const notes: string[] = [
    "Stall speed in a turn rises with sqrt(n), NOT with n: 60° of bank is 2 g and a 41% higher " +
      "stall speed, not 100%.",
    "Level, co-ordinated and steady — a climbing, descending or slipping turn is not this.",
  ];
  if (bankDeg === 0) {
    notes.push("Wings level: the turn radius is infinite and the rate is zero, which is the arithmetic saying it is not turning.");
  }

  let stallInTurnMs: number | null = null;
  if (stallSpeedMs !== undefined) {
    if (!Number.isFinite(stallSpeedMs) || stallSpeedMs <= 0) return null;
    stallInTurnMs = stallSpeedMs * Math.sqrt(loadFactor);
    if (stallInTurnMs > speedMs) {
      notes.push(
        `The stall speed in this turn (${stallInTurnMs.toFixed(1)} m/s) EXCEEDS the flown speed ` +
          `(${speedMs.toFixed(1)} m/s): this bank angle cannot be held at this speed.`,
      );
    }
  }

  return {
    loadFactor,
    radiusM,
    rateRadS,
    periodS: rateRadS > 0 ? (2 * Math.PI) / rateRadS : Infinity,
    stallInTurnMs,
    notes,
  };
}

export interface ClimbGlideResult {
  /** Rate of climb, m/s. Negative is a descent. */
  rocMs: number;
  /** Flight-path angle, degrees. Negative is descending. */
  angleDeg: number;
  /** Glide ratio (horizontal over vertical) when descending. */
  glideRatio: number | null;
  /** Still-air distance from a given height, m. */
  glideRangeM: number | null;
  notes: string[];
}

/**
 * Climb from excess thrust, or the glide that results when thrust is zero.
 *
 *   ROC = V*(T - D)/W   and   sin(gamma) = (T - D)/W
 *
 * The small-angle shortcut gamma ~ (T-D)/W is NOT used: it is fine for an
 * airliner at 3 degrees and wrong for anything steep, and the exact arcsine costs
 * nothing.
 */
export function climbGlide(
  thrustN: number,
  dragN: number,
  weightN: number,
  speedMs: number,
  heightM?: number,
): ClimbGlideResult | null {
  const vals = [thrustN, dragN, weightN, speedMs];
  if (!vals.every(Number.isFinite)) return null;
  if (weightN <= 0 || speedMs <= 0 || dragN < 0 || thrustN < 0) return null;

  const ratio = (thrustN - dragN) / weightN;
  if (ratio > 1 || ratio < -1) return null; // no real flight-path angle
  const gamma = Math.asin(ratio);
  const rocMs = speedMs * Math.sin(gamma);

  const notes: string[] = [
    "Flight-path angle is the exact arcsine of (T − D)/W, not the small-angle shortcut — the " +
      "shortcut is fine at 3° and wrong at 20°.",
  ];

  let glideRatio: number | null = null;
  let glideRangeM: number | null = null;
  if (gamma < 0) {
    glideRatio = Math.abs(1 / Math.tan(gamma));
    if (heightM !== undefined) {
      if (!Number.isFinite(heightM) || heightM < 0) return null;
      glideRangeM = glideRatio * heightM;
      notes.push(
        "Glide range is still air. A headwind or tailwind changes it directly and is not " +
          "modelled here.",
      );
    }
  } else if (thrustN <= dragN) {
    notes.push("Thrust equals drag: level flight, neither climbing nor descending.");
  }

  return { rocMs, angleDeg: (gamma * 180) / Math.PI, glideRatio, glideRangeM, notes };
}
