// The periodic table: what can be COMPUTED or is already held, and nothing else.
//
// This is the first piece of the periodic-table reference, built deliberately without
// any measured property that is not already carried and verified. The standing rule in
// this project is that all data must be real, and the precedent is the refusal to
// build in steam tables because a table reconstructed from memory is unverifiable. A
// 118-element table with ten properties each is about 1,200 measured values, and they
// have to come from a cited source rather than from recollection.
//
// So this module carries exactly two kinds of thing:
//
//   HELD — the element symbols and standard atomic weights already in chemValidate's
//   PERIODIC, which were verified when they were added. The atomic number comes from
//   the ORDER of that table, which is a property of the held data rather than a second
//   list to get wrong: H is the first key, C the sixth, Fe the twenty-sixth.
//
//   COMPUTED — electron configuration, shell occupancy, block, group and period. These
//   follow from the aufbau principle and the structure of the table; they are
//   generated by the rules below, not looked up.
//
// Everything else — melting and boiling points, density, crystal structure, Mohs
// hardness, spectral emission lines, oxidation states, and the element NAMES — is
// listed in ABSENT_PROPERTIES and reported as absent. Guessing any of them to make the
// feature look finished is the one thing this file must not do.

import { PERIODIC } from "./chemValidate";

/** Symbols in atomic-number order — index + 1 IS the atomic number. */
export const ELEMENT_SYMBOLS: readonly string[] = Object.keys(PERIODIC);

export const ELEMENT_COUNT = ELEMENT_SYMBOLS.length;

/** Atomic number for a symbol, or null. Case-sensitive, as chemistry is. */
export function atomicNumber(symbol: string): number | null {
  const i = ELEMENT_SYMBOLS.indexOf(symbol);
  return i < 0 ? null : i + 1;
}

/** Symbol for an atomic number, or null when out of range. */
export function symbolFor(z: number): string | null {
  if (!Number.isInteger(z) || z < 1 || z > ELEMENT_COUNT) return null;
  return ELEMENT_SYMBOLS[z - 1];
}

/** Standard atomic weight, from the held table. */
export function atomicWeight(z: number): number | null {
  const s = symbolFor(z);
  return s === null ? null : PERIODIC[s];
}

// ---------------------------------------------------------------------------
// Electron configuration, generated from the aufbau order
// ---------------------------------------------------------------------------

const SUBSHELL_LETTER = ["s", "p", "d", "f", "g"] as const;

export interface Subshell {
  /** Principal quantum number. */
  n: number;
  /** Azimuthal quantum number: 0 = s, 1 = p, 2 = d, 3 = f. */
  l: number;
  electrons: number;
  /** Capacity, 2(2l+1). */
  capacity: number;
}

/**
 * The aufbau (Madelung) filling order, GENERATED rather than typed out.
 *
 * The rule is that subshells fill in order of increasing n + l, and where two share
 * an n + l, in order of increasing n. Generating it from the rule means the sequence
 * cannot contain a transcription error, and it extends past the current table on its
 * own — which matters, because a hand-typed "1s 2s 2p 3s 3p 4s 3d …" is exactly the
 * kind of list where one transposition hides for years.
 */
export function aufbauOrder(limit = 60): Array<{ n: number; l: number }> {
  const out: Array<{ n: number; l: number }> = [];
  for (let sum = 1; out.length < limit && sum < 30; sum++) {
    // Within a given n + l, n increases — so l decreases.
    for (let l = Math.floor((sum - 1) / 2); l >= 0 && out.length < limit; l--) {
      const n = sum - l;
      if (n > l) out.push({ n, l });
    }
  }
  return out;
}

/**
 * Ground-state electron configuration PREDICTED BY THE AUFBAU PRINCIPLE.
 *
 * READ THE WORD "PREDICTED". About twenty elements have an experimentally measured
 * configuration that differs from the aufbau prediction — chromium and copper are the
 * textbook pair, and there are more among the transition metals, lanthanides and
 * actinides. Those measured configurations are DATA, they are not carried here, and
 * this function does not pretend to know them.
 *
 * That is a real limitation and it is stated wherever the result is shown, rather than
 * being quietly wrong. The aufbau prediction is still worth having: it is what the
 * principle gives, it is what a student is asked to derive, and it is correct for the
 * large majority of elements.
 */
export function electronConfiguration(z: number): Subshell[] | null {
  if (!Number.isInteger(z) || z < 1 || z > ELEMENT_COUNT) return null;
  const out: Subshell[] = [];
  let left = z;
  for (const { n, l } of aufbauOrder()) {
    if (left <= 0) break;
    const capacity = 2 * (2 * l + 1);
    const electrons = Math.min(capacity, left);
    out.push({ n, l, electrons, capacity });
    left -= electrons;
  }
  return out;
}

/** "1s2 2s2 2p6 3s1" — the configuration written out. */
export function configurationString(z: number): string | null {
  const cfg = electronConfiguration(z);
  if (!cfg) return null;
  return cfg.map((s) => `${s.n}${SUBSHELL_LETTER[s.l]}${s.electrons}`).join(" ");
}

/** Atomic numbers of the noble gases, DERIVED from where each p-block row closes. */
export const NOBLE_GAS_NUMBERS: readonly number[] = (() => {
  const out: number[] = [2];
  // A noble gas is the element at which a p subshell completes (and helium, where the
  // 1s shell completes and there is no 1p). Derived rather than listed.
  for (let z = 3; z <= ELEMENT_COUNT; z++) {
    const cfg = electronConfiguration(z);
    if (!cfg) continue;
    const last = cfg[cfg.length - 1];
    if (last.l === 1 && last.electrons === last.capacity) out.push(z);
  }
  return out;
})();

export function isNobleGas(z: number): boolean {
  return NOBLE_GAS_NUMBERS.includes(z);
}

/** "[Ne] 3s1" — the configuration abbreviated to the previous noble gas core. */
export function nobleGasConfiguration(z: number): string | null {
  const cfg = electronConfiguration(z);
  if (!cfg) return null;
  let core = 0;
  for (const g of NOBLE_GAS_NUMBERS) if (g < z) core = g;
  if (core === 0) return configurationString(z);
  const coreCfg = electronConfiguration(core) as Subshell[];
  const coreCount = coreCfg.length;
  const rest = cfg
    .slice(coreCount)
    .map((s) => `${s.n}${SUBSHELL_LETTER[s.l]}${s.electrons}`)
    .join(" ");
  // A subshell the core only partly fills must not be swallowed by the shorthand.
  const partial = cfg[coreCount - 1];
  const corePartial = coreCfg[coreCount - 1];
  const extra =
    partial && corePartial && partial.electrons !== corePartial.electrons
      ? `${partial.n}${SUBSHELL_LETTER[partial.l]}${partial.electrons} `
      : "";
  return `[${symbolFor(core)}] ${extra}${rest}`.trim();
}

/** Electrons per principal shell — the K, L, M, N… counts a Bohr diagram draws. */
export function shellOccupancy(z: number): number[] | null {
  const cfg = electronConfiguration(z);
  if (!cfg) return null;
  const shells: number[] = [];
  for (const s of cfg) {
    while (shells.length < s.n) shells.push(0);
    shells[s.n - 1] += s.electrons;
  }
  return shells;
}

export const SHELL_LETTERS = ["K", "L", "M", "N", "O", "P", "Q"] as const;

// ---------------------------------------------------------------------------
// Where an element sits in the table
// ---------------------------------------------------------------------------

/** Elements per period: 2, 8, 8, 18, 18, 32, 32 — the shape of the table. */
export const PERIOD_LENGTHS: readonly number[] = [2, 8, 8, 18, 18, 32, 32];

export type Block = "s" | "p" | "d" | "f";

export interface Placement {
  z: number;
  period: number;
  /** 1–18, or null for the f-block series, which sit outside the numbered groups. */
  group: number | null;
  block: Block;
  /** True for the lanthanide/actinide rows shown beneath the main table. */
  fSeries: boolean;
}

/**
 * Period, group and block for an element — DERIVED from the table's structure.
 *
 * THE GROUP-3 QUESTION IS NOT SETTLED, and this does not pretend otherwise. Whether
 * lanthanum or lutetium belongs in group 3 (and correspondingly actinium or
 * lawrencium) is a genuine open point of convention that IUPAC has not closed. Taking
 * a side here would present one convention as fact, so instead the whole fifteen-
 * element f series is placed outside the numbered groups — which is how most printed
 * tables show it — and group 3 in periods 6 and 7 is reported as null rather than
 * assigned. The renderer says so.
 */
export function placement(z: number): Placement | null {
  if (!Number.isInteger(z) || z < 1 || z > ELEMENT_COUNT) return null;

  let period = 1;
  let start = 1;
  for (let p = 0; p < PERIOD_LENGTHS.length; p++) {
    const len = PERIOD_LENGTHS[p];
    if (z < start + len) {
      period = p + 1;
      break;
    }
    start += len;
  }
  const i = z - start; // 0-based index within the period
  const len = PERIOD_LENGTHS[period - 1];

  let group: number | null;
  let fSeries = false;
  if (len === 2) {
    group = i === 0 ? 1 : 18;
  } else if (len === 8) {
    group = i <= 1 ? i + 1 : i + 11; // 0,1 -> 1,2 ; 2..7 -> 13..18
  } else if (len === 18) {
    group = i + 1;
  } else {
    // 32: two s-block, fifteen f-block, then fifteen d/p-block from group 4.
    if (i <= 1) group = i + 1;
    else if (i <= 16) {
      group = null;
      fSeries = true;
    } else group = i - 13; // i=17 -> 4 ... i=31 -> 18
  }

  let block: Block;
  if (fSeries) block = "f";
  else if (group === 1 || group === 2 || z === 2) block = "s";
  else if (group !== null && group >= 13) block = "p";
  else block = "d";

  return { z, period, group, block, fSeries };
}

// ---------------------------------------------------------------------------
// What is NOT here
// ---------------------------------------------------------------------------

/**
 * Properties this tool does not carry, and why.
 *
 * Shown to the reader rather than left as a silent gap. A reference that quietly omits
 * a property is indistinguishable from one that has no data for that element, and the
 * difference matters: these are absent because they need a cited source, not because
 * the elements lack them.
 */
export const ABSENT_PROPERTIES: ReadonlyArray<{ name: string; why: string }> = [
  {
    name: "Element name",
    why: "Names are a data list of 118 entries. The symbols and atomic numbers here are held and verified; the names are not, and typing them from memory is exactly the practice this project refuses.",
  },
  {
    name: "Melting and boiling points",
    why: "Measured values needing a cited source; they also depend on pressure, which has to be stated with them.",
  },
  { name: "Density", why: "Measured, and temperature- and phase-dependent, so it cannot be a single number without saying at what." },
  {
    name: "Crystal structure",
    why: "Measured, and needs a stated convention — Strukturbericht or Pearson symbols — before the values mean anything.",
  },
  { name: "Mohs hardness", why: "Measured on an ordinal scale, and undefined for the gases and for several synthetic elements." },
  {
    name: "Spectral emission lines",
    why: "Measured wavelengths, hundreds per element, and the ones worth showing depend on the excitation conditions. This is the property that most needs a citation.",
  },
  {
    name: "Oxidation states",
    why: "A mixture of commonly observed and rarely observed states; which to show is an editorial judgement that needs a source behind it.",
  },
  {
    name: "Measured electron configuration",
    why: "The configurations here are PREDICTED by the aufbau principle. About twenty elements — chromium and copper among them — are measured to differ, and those measurements are not carried.",
  },
];
