// Whether assay.ts's fits deserve to be believed — and whether they SAY SO when
// they don't.
//
// WHY THIS EXISTS (punch list #6 + #9)
// assay.test.ts fits NOISE-FREE data generated by the same model it then fits.
// That is a real test of the optimiser and a useless test of everything else: with
// exact data, exact information goes in, and Levenberg-Marquardt recovers the
// parameters perfectly even from an experiment that could never work at the bench.
// The first probe written for this file confirmed it — a substrate range 8x BELOW
// Km still returned Vmax=100.00 +- 0.00, R^2 = 1.000000.
//
// Add 5% noise — a good day at the bench — and the truth appears. These tests pin
// it, because the caveats assay.ts now ships quote these exact numbers.

import { fitMichaelisMenten, fitHill, michaelisMenten, levenbergMarquardt } from "../assay";

/** Deterministic LCG: real noise, identical every run. Math.random would make
 *  this test flaky and its failures unreproducible. */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => ((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296);
}

const TRUE_VMAX = 100;
const TRUE_KM = 50;

/** Michaelis-Menten data with proportional noise. */
function noisyMM(S: number[], pct: number, seed = 42): number[] {
  const r = rng(seed);
  return S.map((x) => michaelisMenten(TRUE_VMAX, TRUE_KM, x) * (1 + pct * (r() * 2 - 1)));
}

const GOOD = [5, 10, 25, 50, 100, 250, 500]; // up to 10x Km
const BAD = [0.5, 1, 2, 3, 4, 5, 6]; // all well below Km

describe("noise-free data hides a broken experiment — which is why #9 mattered", () => {
  test("with EXACT data even an unusable substrate range fits perfectly", () => {
    // This is the shape of the pre-existing tests. It passes, and it proves
    // nothing about whether the experiment could work.
    const fit = fitMichaelisMenten(BAD, BAD.map((x) => michaelisMenten(TRUE_VMAX, TRUE_KM, x)));
    expect(fit.vmax).toBeCloseTo(TRUE_VMAX, 4);
    expect(fit.km).toBeCloseTo(TRUE_KM, 4);
    expect(fit.rsquared).toBeCloseTo(1, 8);
    // ...and yet the design is hopeless. The caveat is what carries that.
    expect(fit.caveats.join(" ")).toMatch(/SUBSTRATE RANGE TOO LOW/);
  });
});

describe("with realistic noise, the standard error tells the truth and R² does not", () => {
  test("a good substrate range gives a tight, accurate Vmax", () => {
    const fit = fitMichaelisMenten(GOOD, noisyMM(GOOD, 0.05));
    expect(fit.converged).toBe(true);
    expect(fit.vmax).toBeCloseTo(97.8, 0);
    expect(Math.abs(fit.vmaxSE / fit.vmax)).toBeLessThan(0.05); // ~1.4%
    expect(Math.abs(fit.vmax - TRUE_VMAX) / TRUE_VMAX).toBeLessThan(0.05);
    expect(Math.abs(fit.km - TRUE_KM) / TRUE_KM).toBeLessThan(0.1);
  });

  test("an unusable substrate range gives a Vmax with a ~39% standard error", () => {
    const fit = fitMichaelisMenten(BAD, noisyMM(BAD, 0.05));
    // The fitter is honest: the uncertainty is enormous...
    expect(Math.abs(fit.vmaxSE / fit.vmax)).toBeGreaterThan(0.25);
    expect(fit.vmaxSE).toBeGreaterThan(30);
  });

  test("R² CANNOT distinguish the good design from the hopeless one", () => {
    // The single most important fact in this file, and the reason the caveat says
    // "judge by the standard errors, not R²". Both fits look superb by R².
    const good = fitMichaelisMenten(GOOD, noisyMM(GOOD, 0.05));
    const bad = fitMichaelisMenten(BAD, noisyMM(BAD, 0.05));
    expect(good.rsquared).toBeGreaterThan(0.99);
    expect(bad.rsquared).toBeGreaterThan(0.99);
    expect(Math.abs(good.rsquared - bad.rsquared)).toBeLessThan(0.01);
    // Meanwhile the standard error differs by more than an order of magnitude.
    expect(bad.vmaxSE / good.vmaxSE).toBeGreaterThan(10);
  });

  test("the ratio Vmax/Km survives an unsaturated experiment better than either alone", () => {
    // The textbook result: below saturation only the specificity constant is
    // determined. The claim is COMPARATIVE — the ratio is recovered better than
    // its parts — so assert that relationship rather than an absolute tolerance.
    // (An earlier draft demanded |ratio - 2| < 0.05 and failed at 0.057, which
    // said nothing about the science and everything about a number I picked.)
    const bad = fitMichaelisMenten(BAD, noisyMM(BAD, 0.05));
    const ratioErr = Math.abs(bad.vmax / bad.km - TRUE_VMAX / TRUE_KM) / (TRUE_VMAX / TRUE_KM);
    const vmaxErr = Math.abs(bad.vmax - TRUE_VMAX) / TRUE_VMAX;
    const kmErr = Math.abs(bad.km - TRUE_KM) / TRUE_KM;

    expect(ratioErr).toBeLessThan(vmaxErr); // ~2.8% vs ~7.4%
    expect(ratioErr).toBeLessThan(kmErr);
    expect(ratioErr).toBeLessThan(0.05);

    // And the ratio is determined FAR more precisely than Vmax is: that is the
    // whole reason the caveat says to report Vmax/Km instead.
    expect(Math.abs(bad.vmaxSE / bad.vmax)).toBeGreaterThan(5 * ratioErr);
  });
});

describe("the caveats fire when they should and stay quiet when they shouldn't", () => {
  test("a hopeless range is named explicitly, with the numbers", () => {
    const fit = fitMichaelisMenten(BAD, noisyMM(BAD, 0.05));
    const text = fit.caveats.join(" ");
    expect(text).toMatch(/SUBSTRATE RANGE TOO LOW/);
    expect(text).toMatch(/BELOW the fitted Km/);
    expect(text).toMatch(/Only their ratio Vmax\/Km is meaningful/);
    expect(text).toMatch(/5×Km/);
  });

  test("a good range does NOT get the range warning — or the caveat means nothing", () => {
    const fit = fitMichaelisMenten(GOOD, noisyMM(GOOD, 0.05));
    const text = fit.caveats.join(" ");
    expect(text).not.toMatch(/SUBSTRATE RANGE TOO LOW/);
    expect(text).not.toMatch(/range is marginal/);
  });

  test("a marginal range gets the marginal warning, not the fatal one", () => {
    const MARGINAL = [5, 10, 20, 40, 60, 80, 100]; // to 2x Km
    const text = fitMichaelisMenten(MARGINAL, noisyMM(MARGINAL, 0.05)).caveats.join(" ");
    expect(text).toMatch(/range is marginal/);
    expect(text).not.toMatch(/SUBSTRATE RANGE TOO LOW/);
  });

  test("every fit warns that R² is a poor guide and least squares cannot judge the model", () => {
    for (const fit of [fitMichaelisMenten(GOOD, noisyMM(GOOD, 0.05)), fitHill(GOOD, noisyMM(GOOD, 0.05))]) {
      const text = fit.caveats.join(" ");
      expect(text).toMatch(/R² is a poor guide/);
      expect(text).toMatch(/cannot tell you the model is wrong/);
      expect(text).toMatch(/LOCAL optimiser/);
    }
  });

  test("no degrees of freedom is called out rather than reported as a perfect fit", () => {
    // 2 points, 2 parameters: the model threads both exactly. R² = 1 means nothing.
    const S = [10, 20];
    const fit = fitMichaelisMenten(S, S.map((x) => michaelisMenten(TRUE_VMAX, TRUE_KM, x)));
    expect(fit.caveats.join(" ")).toMatch(/no degrees of freedom/);
  });

  test("a non-converging fit says so in capitals, first", () => {
    // Force failure with a pathological model and a hard iteration cap.
    const x = [1, 2, 3, 4, 5];
    const y = [1, 50, 2, 90, 3];
    const fit = levenbergMarquardt(x, y, ([a, b], xi) => a * Math.sin(b * xi * 1e3), [1, 1], { maxIter: 2 });
    if (!fit.converged) expect(fit.caveats[0]).toMatch(/DID NOT CONVERGE/);
  });
});

describe("fits are robust to the noise a real bench produces", () => {
  test("Vmax stays within 10% across noise levels and seeds", () => {
    for (const pct of [0.02, 0.05, 0.1]) {
      for (const seed of [1, 7, 42, 99]) {
        const fit = fitMichaelisMenten(GOOD, noisyMM(GOOD, pct, seed));
        expect(fit.converged).toBe(true);
        expect(Math.abs(fit.vmax - TRUE_VMAX) / TRUE_VMAX).toBeLessThan(0.1);
      }
    }
  });

  test("Hill recovers n ≈ 1 from Michaelis-Menten data (no false cooperativity)", () => {
    // A real risk: the Hill model has a spare parameter and can invent
    // cooperativity from noise. It should not.
    const fit = fitHill(GOOD, noisyMM(GOOD, 0.05));
    expect(fit.hill).toBeGreaterThan(0.85);
    expect(fit.hill).toBeLessThan(1.15);
  });
});
