// manifest.xml's <Version> must track package.json.
//
// WHY THIS EXISTS
// The two are maintained by hand and drifted four releases apart (package.json at
// 1.69.0, manifest.xml still at 1.65.2.0) because `npm version` bumps one and not
// the other. scripts/package.ps1 does not stamp the version — it copies the
// manifest verbatim — so the stale number propagated silently into all three
// install packs (host, Windows, macOS), each shipping a manifest labelled 1.65.2.0
// that loads 1.69.0 code.
//
// The harm is limited: the manifest points at GitHub Pages, so users always load
// current code regardless of this number. But a version label that lies is exactly
// the class of thing this project keeps finding, and "remember to bump it" already
// failed four times in a row. Machines are better at this than people.

import * as fs from "fs";
import * as path from "path";

const ROOT = path.join(__dirname, "..", "..", "..");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")) as { version: string };

/** The <Version> of an Office manifest, or null when absent/unreadable. */
function manifestVersion(file: string): string | null {
  if (!fs.existsSync(file)) return null;
  const m = /<Version>([^<]*)<\/Version>/.exec(fs.readFileSync(file, "utf8"));
  return m ? m[1] : null;
}

describe("manifest version tracks package.json", () => {
  // BOTH manifests, and manifest.prod.xml is the one that matters:
  //   manifest.xml       -> the localhost:3000 DEV manifest, for local sideload
  //   manifest.prod.xml  -> what webpack publishes and the install packs ship
  // An earlier version of this test checked only manifest.xml. Bumping that one
  // alone left every shipped artifact on the old number and the test still went
  // green — it was checking the manifest nobody installs. Checking the file that
  // is easiest to reach is not the same as checking the file that ships.
  const MANIFESTS = ["manifest.xml", "manifest.prod.xml"];

  test.each(MANIFESTS)("%s matches package.json", (file) => {
    // Office manifests take four parts; ours is the semver plus a trailing .0.
    expect(manifestVersion(path.join(ROOT, file))).toBe(`${pkg.version}.0`);
  });

  test.each(MANIFESTS)("%s has a well-formed 4-part Office version", (file) => {
    expect(manifestVersion(path.join(ROOT, file))).toMatch(/^\d+\.\d+\.\d+\.\d+$/);
  });

  test("the dev and prod manifests point at different hosts, as intended", () => {
    // Guards against the two being conflated. If manifest.prod.xml ever picked up
    // localhost, every install pack would ship an add-in that loads nothing —
    // which has bitten this project before.
    const dev = fs.readFileSync(path.join(ROOT, "manifest.xml"), "utf8");
    const prod = fs.readFileSync(path.join(ROOT, "manifest.prod.xml"), "utf8");
    expect(dev).toContain("localhost:3000");
    expect(prod).not.toContain("localhost:3000");
  });

  test("release packs, if present, are not stale", () => {
    // The packs are build artifacts and may be absent on a fresh clone — that is
    // fine. But a pack that EXISTS while carrying a different version is one an
    // installer could hand to a user, so it must not be silently wrong.
    const packs = [
      "release/formula-inserter-host/manifest.xml",
      "release/formula-inserter-windows/manifest.xml",
      "release/formula-inserter-mac/manifest.xml",
    ];
    const stale: string[] = [];
    for (const p of packs) {
      const v = manifestVersion(path.join(ROOT, p));
      if (v !== null && v !== `${pkg.version}.0`) stale.push(`${p} = ${v}`);
    }
    expect(stale).toEqual([]);
  });

  test("the hosted pack's version.json, if present, matches too", () => {
    // version.json is the USER UPDATE TRIGGER — the one number that decides
    // whether anyone is offered the fix at all. It is generated by the build, so
    // a mismatch here means the pack was assembled from a stale dist/.
    const f = path.join(ROOT, "release/formula-inserter-host/web/version.json");
    if (!fs.existsSync(f)) return;
    expect(JSON.parse(fs.readFileSync(f, "utf8"))).toEqual({ version: pkg.version });
  });
});
